In [2]:
import numpy as np
import pandas as pd

In [3]:
newdf=pd.DataFrame(np.random.rand(20,5))

In [4]:
newdf.to_numpy()

array([[0.32853128, 0.49468891, 0.41971146, 0.5452194 , 0.26816281],
       [0.1242533 , 0.79830502, 0.06811665, 0.27039168, 0.24379648],
       [0.86222379, 0.22547591, 0.22382214, 0.80440299, 0.99557343],
       [0.62311889, 0.70776553, 0.50934517, 0.63778484, 0.60979959],
       [0.05019657, 0.21753378, 0.06669189, 0.30273808, 0.97638769],
       [0.2079513 , 0.8736488 , 0.73655949, 0.86118525, 0.22298763],
       [0.30546464, 0.08971654, 0.99958851, 0.53773569, 0.78580957],
       [0.46329267, 0.85721899, 0.79717947, 0.81438635, 0.35421659],
       [0.53057587, 0.57686497, 0.15152562, 0.29059791, 0.93519982],
       [0.71178156, 0.164157  , 0.18379867, 0.88432874, 0.72201841],
       [0.58153308, 0.81589009, 0.11349109, 0.2784999 , 0.02052467],
       [0.77037988, 0.6354972 , 0.60134118, 0.95444108, 0.15669348],
       [0.9549228 , 0.69820626, 0.09732731, 0.17006872, 0.18255269],
       [0.88078303, 0.59110116, 0.23543044, 0.59879186, 0.66467933],
       [0.91384748, 0.97044716, 0.63462554, 0.51734322, 0.68846352],
       [0.54904561, 0.60328358, 0.2586978 , 0.1672823 , 0.01198293],
       [0.30445145, 0.31777616, 0.58642221, 0.62597475, 0.58348646],
       [0.75288403, 0.37275445, 0.90149223, 0.72795265, 0.15069302],
       [0.68260321, 0.9506752 , 0.88931392, 0.07019085, 0.53113332],
       [0.5918781 , 0.48682189, 0.0223069 , 0.59435359, 0.46196773]])

In [5]:
newdf

           0         1         2         3         4
0   0.328531  0.494689  0.419711  0.545219  0.268163
1   0.124253  0.798305  0.068117  0.270392  0.243796
2   0.862224  0.225476  0.223822  0.804403  0.995573
3   0.623119  0.707766  0.509345  0.637785  0.609800
4   0.050197  0.217534  0.066692  0.302738  0.976388
5   0.207951  0.873649  0.736559  0.861185  0.222988
6   0.305465  0.089717  0.999589  0.537736  0.785810
7   0.463293  0.857219  0.797179  0.814386  0.354217
8   0.530576  0.576865  0.151526  0.290598  0.935200
9   0.711782  0.164157  0.183799  0.884329  0.722018
10  0.581533  0.815890  0.113491  0.278500  0.020525
11  0.770380  0.635497  0.601341  0.954441  0.156693
12  0.954923  0.698206  0.097327  0.170069  0.182553
13  0.880783  0.591101  0.235430  0.598792  0.664679
14  0.913847  0.970447  0.634626  0.517343  0.688464
15  0.549046  0.603284  0.258698  0.167282  0.011983
16  0.304451  0.317776  0.586422  0.625975  0.583486
17  0.752884  0.372754  0.901492  0.727953  0.150693
18  0.682603  0.950675  0.889314  0.070191  0.531133
19  0.591878  0.486822  0.022307  0.594354  0.461968

In [6]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.328531,0.124253,0.862224,0.623119,0.050197,0.207951,0.305465,0.463293,0.530576,0.711782,0.581533,0.770380,0.954923,0.880783,0.913847,0.549046,0.304451,0.752884,0.682603,0.591878
1,0.494689,0.798305,0.225476,0.707766,0.217534,0.873649,0.089717,0.857219,0.576865,0.164157,0.815890,0.635497,0.698206,0.591101,0.970447,0.603284,0.317776,0.372754,0.950675,0.486822
2,0.419711,0.068117,0.223822,0.509345,0.066692,0.736559,0.999589,0.797179,0.151526,0.183799,0.113491,0.601341,0.097327,0.235430,0.634626,0.258698,0.586422,0.901492,0.889314,0.022307
3,0.545219,0.270392,0.804403,0.637785,0.302738,0.861185,0.537736,0.814386,0.290598,0.884329,0.278500,0.954441,0.170069,0.598792,0.517343,0.167282,0.625975,0.727953,0.070191,0.594354
4,0.268163,0.243796,0.995573,0.609800,0.976388,0.222988,0.785810,0.354217,0.935200,0.722018,0.020525,0.156693,0.182553,0.664679,0.688464,0.011983,0.583486,0.150693,0.531133,0.461968

In [7]:
newdf.sort_index(axis=0,ascending=False)

           0         1         2         3         4
19  0.591878  0.486822  0.022307  0.594354  0.461968
18  0.682603  0.950675  0.889314  0.070191  0.531133
17  0.752884  0.372754  0.901492  0.727953  0.150693
16  0.304451  0.317776  0.586422  0.625975  0.583486
15  0.549046  0.603284  0.258698  0.167282  0.011983
14  0.913847  0.970447  0.634626  0.517343  0.688464
13  0.880783  0.591101  0.235430  0.598792  0.664679
12  0.954923  0.698206  0.097327  0.170069  0.182553
11  0.770380  0.635497  0.601341  0.954441  0.156693
10  0.581533  0.815890  0.113491  0.278500  0.020525
9   0.711782  0.164157  0.183799  0.884329  0.722018
8   0.530576  0.576865  0.151526  0.290598  0.935200
7   0.463293  0.857219  0.797179  0.814386  0.354217
6   0.305465  0.089717  0.999589  0.537736  0.785810
5   0.207951  0.873649  0.736559  0.861185  0.222988
4   0.050197  0.217534  0.066692  0.302738  0.976388
3   0.623119  0.707766  0.509345  0.637785  0.609800
2   0.862224  0.225476  0.223822  0.804403  0.995573
1   0.124253  0.798305  0.068117  0.270392  0.243796
0   0.328531  0.494689  0.419711  0.545219  0.268163

In [8]:
type(newdf[0])

pandas.core.series.Series